name: perfect_first_synth
description: A project with ambitions of becoming the perfect first synthesizer

publish_to: 'none'
version: 1.2.0

repository: https://github.com/oshibka404/perfect-first-synth
issue_tracker: https://github.com/oshibka404/perfect-first-synth/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
