name: synt
description: A project with ambitions of becoming the perfect first synthesizer

publish_to: 'none'
version: 1.4.0

repository: https://github.com/oshibka404/synt
issue_tracker: https://github.com/oshibka404/synt/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^1.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
