name: perfect_first_synth
description: A project with ambitions of becoming the perfect first synthesizer

publish_to: 'none'
version: 0.0.1

repository: https://github.com/oshibka404/perfect-first-synth
issue_tracker: https://github.com/oshibka404/perfect-first-synth/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.0.0

flutter:
  uses-material-design: true
