// TODO: move it to json

import 'arpeggio.dart';
import 'player_action.dart';

List<Arpeggio> shit = [
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction.stop(),
    null,
  ]),
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 2),
    PlayerAction(stepOffset: 3),
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 1),
  ]),
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 1),
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 3),
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction.stop(),
    null,
    PlayerAction(stepOffset: 5),
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    null,
  ]),
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 1),
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 3),
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    PlayerAction(stepOffset: 5),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: -1),
  ]),
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 2),
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 5),
    PlayerAction(stepOffset: 7),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    PlayerAction(stepOffset: 5),
    null,
    PlayerAction.stop(),
    PlayerAction(stepOffset: 1),
  ]),
  Arpeggio([
    PlayerAction(),
    null,
    PlayerAction(stepOffset: 2),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 2),
    null,
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    null,
    PlayerAction(stepOffset: 5),
    null,
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 3),
    PlayerAction.stop(),
  ]),
  Arpeggio([
    PlayerAction(),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 2),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 2),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 5),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 4),
    PlayerAction.stop(),
    PlayerAction(stepOffset: 3),
    PlayerAction.stop(),
  ]),
];
