// TODO: move it to json
// TODO: build it into Preset
import 'arpeggio.dart';
import 'player_action.dart';

Map<String, List<Arpeggio>> arpeggio_bank = {
  'harmony': [
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      null,
      null,
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      null,
      null,
      PlayerAction(velocity: .7),
      PlayerAction.stop(),
      null,
      null,
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      null,
      null,
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(velocity: .7),
      PlayerAction.stop(),
      PlayerAction(velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .3),
      PlayerAction.stop(),
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(velocity: .7),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 9, velocity: .7),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7, velocity: .5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4, velocity: .3),
      PlayerAction.stop(),
    ]),
  ],
  'bass': [
    Arpeggio([
      PlayerAction(),
      null,
      null,
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      null,
      null,
      PlayerAction.stop(),
      PlayerAction(velocity: .7),
      null,
      null,
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      null,
      null,
      PlayerAction.stop(),
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .7),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .7),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
      PlayerAction(velocity: .5),
      PlayerAction.stop(),
      PlayerAction(velocity: .2),
      PlayerAction.stop(),
    ])
  ],
  'melody': [
    Arpeggio([
      PlayerAction(),
      null,
      PlayerAction.stop(),
      null,
      PlayerAction(stepOffset: 7),
      null,
      PlayerAction.stop(),
      null,
      PlayerAction(stepOffset: 4),
      null,
      PlayerAction.stop(),
      null,
      PlayerAction(stepOffset: 2),
      null,
      PlayerAction.stop(),
      null,
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(),
      null,
      PlayerAction(stepOffset: 5),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 5),
      null,
      PlayerAction(stepOffset: 4),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4),
      null,
      PlayerAction(stepOffset: 2),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 2),
      null,
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 2),
      PlayerAction(stepOffset: 3),
      PlayerAction(stepOffset: 2),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 3),
      PlayerAction(stepOffset: 4),
      PlayerAction(stepOffset: 3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4),
      PlayerAction(stepOffset: 5),
      PlayerAction(stepOffset: 4),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 2),
      PlayerAction(stepOffset: 1),
    ]),
    Arpeggio([
      PlayerAction(),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 4),
      PlayerAction(stepOffset: 3),
      PlayerAction(stepOffset: 2),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 5),
      PlayerAction(stepOffset: 4),
      PlayerAction(stepOffset: 3),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 6),
      PlayerAction(stepOffset: 5),
      PlayerAction(stepOffset: 4),
      PlayerAction.stop(),
      PlayerAction(stepOffset: 7),
      PlayerAction(stepOffset: 6),
    ]),
  ],
};
