name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - name: Install dependencies
      run: flutter pub get
    - name: Static analysis
      run: flutter analyze
    - name: Run tests
      run: flutter test
